name: Docker Registry Push and Deploy on Tags

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push:
    name: "Docker Registry Push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: registry.raclette.ovh
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ format('{0}-{1}', 'registry.raclette.ovh/countdownly:run', github.run_number) }}, registry.raclette.ovh/countdownly:latest

  sonarqube:
    name: Quality-Gate
    runs-on: ubuntu-latest
    permissions: read-all
    needs: push
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  create_release:
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    needs: [push, sonarqube]
    steps:
      - name: Get the tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          release_name: Release ${{ steps.tag.outputs.TAG_NAME }}
          body: |
            Release for version ${{ steps.tag.outputs.TAG_NAME }}
          draft: false
          prerelease: false

  deploy_production:
    name: "Deploy production to server"
    runs-on: ubuntu-latest
    needs: [push, sonarqube]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: cd /docker/docker-compose/countdownly && docker compose pull && docker compose down -v && docker compose up -d
